version: '3.9'

services:
  dashboard:
    build: .
    image: hsl-dashboard:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
